### ISSUE TITLE
Generate custom token pool via CLI in dev network

### ISSUE THREAD

**Issue by stanleyjones** [liftedinit/roadmap#14]
Requirements TBD. Just a placeholder for now.

**Comment by tysloan** [comment]
Description: This is for Liftoff Program members and Web2/3 developers who need a custom token on an existing network. The generate custom tokens feature will benefit users who want them for company equity issuances, reward tokens, utility tokens, and more. This functionality should be achievable via the CLI. Users should be able to generate an initial custom token pool, like we do at genesis, but without being able to modify the supply afterwards. This story is to send the feature to the dev network.

Story ROI:  
Customer Need: A Liftoff Program team has requested a way to generate a custom token on an existing network to replace their in-app currency with a blockchain-based token.

Business Objective: Enabling more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As a developer, I want to generate custom tokens so that end-users can transact them.**

- [ ] Should be achievable via Rust Library.
- [ ] Should be able to limit the scope to the Manifest dev network.
- [ ] Should be able to generate a new symbol (3-5 letter limit).
- [ ] Should present an error message if the symbol is already taken on the network.
- [ ] Should be able to input the set number of custom tokens that will be generated in the pool.
- [ ] Should be able to transact custom tokens after they are generated.
- [ ] Should be able to be demoed in the dev network.
- [ ] Should NOT be able to modify the supply afterwards.
- [ ] Should NOT include minting and burning custom tokens.
- [ ] Should NOT include documentation requirements.
- [ ] Should NOT include sending to QA/staging.

[PRD](https://docs.google.com/document/d/1RhJcAMI_kS1wPsAhAL9STbk1r20cplPUbuwSVee3bRQ/edit?usp=sharing).

----------------------
Tasks (adapted from @fmorency notes)

- [ ] Define specification.
- [ ] Write implementation.
       a. many-rs & many-js
       b. many-framework & Alberto
- [ ] Write tests.
- [ ] Write documentation.
- [ ] Propagate to the dev environment.
- [ ] Demo the story to the team (local & dev network) (Feature branch).

**Comment by fmorency** [comment]
Following our discussions

Flow:

1. Define the specification
2. Write implementation 
  a. many-rs & many-js
  b. many-framework and Alberto
4. Write tests
5. Demo to product (local & dev network) (Feature branch)
  a. If OK for the Product team, continue
  b. ELSE, return to 2
7. Write documentation
8. Send to QA/Staging for testing (RC)
9. Fix bugs & etc
10. Send to production (Release)

For this specific story, I think that **1 to 4** is a 2-week sprint deliverable for both backend and front-end Eng, i.e., demo the first implementation of this feature to the team (CLI and UI) and get feedback.

@jgryffindor, what amount of work is reasonable for this sprint, knowing that we will need on-demand dev networks and a QA/Staging network at some point?

Re-assess status after sprint.

- #21 depends on this story
- #21 can start as soon as the specification is defined
- #21 will need the implementation from this story



I'll let the front-end folks write about the front-end part of #21.

The front-end te can start mock-ups immediately or as soon as the specification is defined, maybe even before.

Eng can start the JS implementation as soon as the specification is defined (2. above)



The rest depends on #14, as it needs the backend implementation to work and test, although we could put some effort into our mock server. I would have to think about it to see if it would be more efficient. WDYT @hansl?

**Comment by fmorency** [comment]
I should also point out that a design (specification or otherwise) CAN BE a sprint deliverable.

**Comment by jgryffindor** [comment]
I think it's reasonable in this sprint to deploy a new dev network for demos and testing features. It will contain a CDN node, ledger network of 4 nodes and kvstore network of 4 nodes and I can aim to have it up by next Thursday/Friday.

For QA/Staging networks we will need to deploy more nodes so likely a few weeks out to begin those.

**Comment by tysloan** [comment]
I've updated the requirements and added the Tasks from yesterday's discussion and the above notes. Please add/edit any appropriate Tasks that will be required for this story @fmorency & @jgryffindor.
